---
title: "Weekly Summary Template"
author: "Author Name"
title-block-banner: true
title-block-style: default
toc: true
#format: html
format: pdf
---

---

## Tuesday, Jan 17

::: {.callout-important}
## TIL

Include a _very brief_ summary of what you learnt in this class here. 

Today, I learnt the following concepts in class:

1. Reading files into a csv
1. dplyr
1. ggplot2
:::

Provide more concrete details here. You can also use footenotes[^footnote] if you like

* We created a fake dataset and learned how to read a csv file like the dataset into r. 
* We also learned about what makes a dataset clean and what properties a clean dataset looks like.
* We then talked about some different datasets that are prebuilt into R.
* We finished by talking about graphing utilities like ggplot2.


## Thursday, Jan 19



::: {.callout-important}
## TIL

Include a _very brief_ summary of what you learnt in this class here. 

Today, I learnt the following concepts in class:

1. Item 1
1. Item 2
1. Item 3
:::

Provide more concrete details here, e.g., 

In class we learnt how to use the `map` function to create multiple regression diagnostic plots




[^footnote]: You can include some footnotes here